import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Conversation Tree · Speak English about yourself",
    short_name: "Conversation Tree",
    description:
      "Learn everyday English by branching through real conversations like a skill tree.",
    start_url: "/",
    display: "standalone",
    background_color: "#0a0b12",
    theme_color: "#6366f1",
    icons: [
      {
        // Generated by app/icon.tsx — 512x512 PNG.
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        // Generated by app/apple-icon.tsx — full-bleed 180x180 PNG.
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
