// Seed specs for AI-generated stories. Each becomes one long conversation via
// /api/generate-story. Hand-written "featured" stories live in src/data/stories.ts
// and are NOT duplicated here. Ids are prefixed "g-" to avoid collisions.

export const seeds = [
  // ───────── Self Introduction ─────────
  { id: "g-si-basics", topicId: "self-intro", title: "Nice to Meet You", title_ja: "はじめまして", emoji: "👋", difficulty: "beginner",
    summary: "The basics: name, work, where you live.", summary_ja: "名前・仕事・住んでいる場所の基本。",
    brief: "A first meeting. The AI asks Kaito to introduce himself: his name, that he's an engineer at Nissan, where he lives (Atsugi), and a little about what he likes." },
  { id: "g-si-name", topicId: "self-intro", title: "About My Name", title_ja: "名前について", emoji: "🪪", difficulty: "beginner",
    summary: "Your name and how to say it.", summary_ja: "名前とその読み方。",
    brief: "Small talk about Kaito's name — how to pronounce 'Kaito', what it's like having his name with English speakers, nicknames." },
  { id: "g-si-atsugi", topicId: "self-intro", title: "Where I'm From", title_ja: "出身・在住", emoji: "📍", difficulty: "intermediate",
    summary: "Living in Atsugi, Kanagawa.", summary_ja: "神奈川県厚木市での暮らし。",
    brief: "Kaito talks about living in Atsugi, Kanagawa — what the area is like, why he lives there (close to Nissan's tech center), what he likes about it." },
  { id: "g-si-personality", topicId: "self-intro", title: "What I'm Like", title_ja: "性格", emoji: "🧩", difficulty: "intermediate",
    summary: "Your personality and how you think.", summary_ja: "性格や考え方。",
    brief: "Kaito describes his personality: curious, logical, calm, likes solving hard problems, prefers creating over consuming, enjoys deep conversations." },
  { id: "g-si-day", topicId: "self-intro", title: "A Day in My Life", title_ja: "一日の流れ", emoji: "🕗", difficulty: "intermediate",
    summary: "Your typical day, start to finish.", summary_ja: "典型的な一日の流れ。",
    brief: "Kaito walks through a normal weekday: morning, commuting, work at Nissan, evening, side projects before bed." },

  // ───────── Weekend ─────────
  { id: "g-wk-cafe", topicId: "weekend", title: "Working at a Cafe", title_ja: "カフェで作業", emoji: "☕", difficulty: "beginner",
    summary: "Coding at a cafe on a day off.", summary_ja: "休日にカフェでコーディング。",
    brief: "Kaito likes going to a cafe on weekends to code or think. Talk about his favorite cafe, what he orders, why he likes working there." },
  { id: "g-wk-relax", topicId: "weekend", title: "A Lazy Sunday", title_ja: "のんびり日曜", emoji: "😌", difficulty: "beginner",
    summary: "Doing nothing and recharging.", summary_ja: "何もせず充電する日。",
    brief: "A slow Sunday — sleeping in, YouTube, snacks, recharging after a busy week. Keep it light and relatable." },
  { id: "g-wk-shopping", topicId: "weekend", title: "Weekend Errands", title_ja: "週末の買い物", emoji: "🛒", difficulty: "intermediate",
    summary: "Shopping and small errands.", summary_ja: "買い物やちょっとした用事。",
    brief: "Kaito runs errands on the weekend — groceries, maybe a gadget store. Talk about what he buys and his shopping habits." },

  // ───────── Work & Career ─────────
  { id: "g-wk-job", topicId: "work", title: "What I Do at Nissan", title_ja: "日産での仕事", emoji: "🏢", difficulty: "intermediate",
    summary: "Your role on the AD/ADAS team.", summary_ja: "AD/ADASチームでの役割。",
    brief: "Kaito explains his job as an AD/ADAS engineer at Nissan in simple terms — what AD/ADAS means, what he works on day to day." },
  { id: "g-wk-parking", topicId: "work", title: "The Parking PoC", title_ja: "自動駐車のPoC", emoji: "🅿️", difficulty: "advanced",
    summary: "Your auto-parking proof of concept.", summary_ja: "自動駐車のPoCの話。",
    brief: "Kaito talks about the auto-parking proof-of-concept he works on: why parking is hard for a car, what's challenging, what excites him about it." },
  { id: "g-wk-newgrad", topicId: "work", title: "Joining as a New Grad", title_ja: "新卒入社", emoji: "🌱", difficulty: "intermediate",
    summary: "Starting your career in 2026.", summary_ja: "2026年にキャリアを始めた話。",
    brief: "Kaito just joined Nissan as a new graduate in April 2026. Talk about how it feels, what surprised him, what he's learning." },
  { id: "g-wk-team", topicId: "work", title: "My Team", title_ja: "チームのこと", emoji: "🤝", difficulty: "intermediate",
    summary: "Your colleagues and how you work.", summary_ja: "同僚や働き方。",
    brief: "Kaito describes his team and colleagues at the AD/ADAS Advanced Technology Development department, how they collaborate, the atmosphere." },
  { id: "g-wk-commute", topicId: "work", title: "Commuting to NATC", title_ja: "NATCへの通勤", emoji: "🚉", difficulty: "beginner",
    summary: "Getting to the tech center.", summary_ja: "技術センターへの通勤。",
    brief: "Kaito's commute to NATC (Nissan's tech center in Atsugi) — how he gets there, how long it takes, what he does on the way." },

  // ───────── Research ─────────
  { id: "g-rs-vlm", topicId: "research", title: "My VLM Research", title_ja: "VLM研究", emoji: "🔬", difficulty: "advanced",
    summary: "Vision-Language Models for driving.", summary_ja: "運転のためのVLM研究。",
    brief: "Kaito explains his research on Vision-Language Models (VLMs) for driver assistance, in friendly terms — what a VLM is and why it helps a car explain itself." },
  { id: "g-rs-explainable", topicId: "research", title: "Explainable AI", title_ja: "説明可能なAI", emoji: "💡", difficulty: "advanced",
    summary: "Why AI should explain itself.", summary_ja: "AIが理由を説明できる重要性。",
    brief: "Kaito talks about why 'explainable' and 'risk-aware' driver assistance matters — why it's important that a car can explain why it acted, especially for safety and trust." },
  { id: "g-rs-master", topicId: "research", title: "My Master's at Kyushu", title_ja: "九大での修士", emoji: "🎓", difficulty: "intermediate",
    summary: "Grad school and your thesis.", summary_ja: "大学院と研究の話。",
    brief: "Kaito's master's program in Automotive Science at Kyushu University — what he studied, his research, what grad school was like." },
  { id: "g-rs-why", topicId: "research", title: "Why I Love Research", title_ja: "研究が好きな理由", emoji: "❤️", difficulty: "intermediate",
    summary: "What draws you to research.", summary_ja: "研究に惹かれる理由。",
    brief: "Why Kaito prefers research over pure industry work — exploring deep questions, creating knowledge, the joy of solving hard problems." },
  { id: "g-rs-present", topicId: "research", title: "Presenting Research", title_ja: "研究発表", emoji: "🎤", difficulty: "advanced",
    summary: "Talking about your work to others.", summary_ja: "自分の研究を人に話す。",
    brief: "Kaito talks about presenting his research — at seminars or conferences, doing it in English, nerves, and what he's learned about explaining complex ideas simply." },

  // ───────── Autonomous Driving ─────────
  { id: "g-ad-future", topicId: "autonomous", title: "The Future of Driving", title_ja: "運転の未来", emoji: "🔮", difficulty: "intermediate",
    summary: "Where self-driving is heading.", summary_ja: "自動運転の行方。",
    brief: "Kaito shares his view on where autonomous driving is heading and how soon fully self-driving cars might be common." },
  { id: "g-ad-safety", topicId: "autonomous", title: "Is It Safe?", title_ja: "安全なの？", emoji: "🛡️", difficulty: "intermediate",
    summary: "Trust and safety in self-driving.", summary_ja: "自動運転の信頼と安全。",
    brief: "A conversation about whether self-driving cars are safe, would Kaito trust one, and how engineers think about safety." },
  { id: "g-ad-levels", topicId: "autonomous", title: "Levels of Autonomy", title_ja: "自動運転レベル", emoji: "📶", difficulty: "advanced",
    summary: "What 'Level 2', 'Level 4' mean.", summary_ja: "レベル2・4などの意味。",
    brief: "Kaito explains the levels of driving automation in simple words and where today's cars actually are." },
  { id: "g-ad-japan", topicId: "autonomous", title: "Driving in Japan", title_ja: "日本の道路", emoji: "🗾", difficulty: "intermediate",
    summary: "Why Japanese roads are tricky.", summary_ja: "日本の道路が難しい理由。",
    brief: "Why autonomous driving is challenging on narrow, busy Japanese roads, and how that shapes Kaito's work." },
  { id: "g-ad-tesla", topicId: "autonomous", title: "Tesla vs Nissan", title_ja: "テスラと日産", emoji: "⚡", difficulty: "advanced",
    summary: "Comparing approaches to autonomy.", summary_ja: "自動運転へのアプローチ比較。",
    brief: "Kaito compares how Tesla and traditional makers like Nissan approach autonomous driving — cameras vs sensors, philosophy, what he admires and questions." },

  // ───────── Technology ─────────
  { id: "g-tc-gadgets", topicId: "technology", title: "My Favorite Gadgets", title_ja: "好きなガジェット", emoji: "📱", difficulty: "beginner",
    summary: "The devices you can't live without.", summary_ja: "手放せないデバイス。",
    brief: "Kaito talks about his favorite gadgets and devices and why he likes them." },
  { id: "g-tc-llm", topicId: "technology", title: "Living with LLMs", title_ja: "LLMのある生活", emoji: "🧠", difficulty: "intermediate",
    summary: "How you use ChatGPT-style tools.", summary_ja: "ChatGPT的ツールの使い方。",
    brief: "How Kaito uses large language models day to day — coding, studying English, organizing ideas — and what he thinks about them." },
  { id: "g-tc-langs", topicId: "technology", title: "Programming Languages", title_ja: "プログラミング言語", emoji: "⌨️", difficulty: "intermediate",
    summary: "TypeScript, Python, and friends.", summary_ja: "TypeScriptやPythonの話。",
    brief: "Kaito's favorite programming languages (TypeScript, Python) and what he likes building with each." },
  { id: "g-tc-space", topicId: "technology", title: "Space & SpaceX", title_ja: "宇宙とSpaceX", emoji: "🚀", difficulty: "intermediate",
    summary: "Your interest in space tech.", summary_ja: "宇宙技術への興味。",
    brief: "Kaito's interest in SpaceX and space technology — what excites him, and how it connects to his love of ambitious engineering." },

  // ───────── Side Projects ─────────
  { id: "g-pj-globe", topicId: "projects", title: "AI Globe Gesture Space", title_ja: "AI Globe Gesture Space", emoji: "🌐", difficulty: "advanced",
    summary: "Your hand-gesture 3D globe project.", summary_ja: "手で操作する3Dグローブ。",
    brief: "Kaito describes his side project: an interactive 3D globe controlled by hand gestures, with AI knowledge nodes, built with Python, OpenCV and MediaPipe." },
  { id: "g-pj-thisapp", topicId: "projects", title: "This English App", title_ja: "この英語アプリ", emoji: "🌳", difficulty: "intermediate",
    summary: "Building Conversation Tree.", summary_ja: "Conversation Tree を作る。",
    brief: "Kaito talks about building this very app — Conversation Tree, an English learning app — why he made it and what he wants it to become." },
  { id: "g-pj-why", topicId: "projects", title: "Why I Build Things", title_ja: "なぜ作るのか", emoji: "🛠️", difficulty: "intermediate",
    summary: "What drives your side projects.", summary_ja: "個人開発の原動力。",
    brief: "Why Kaito builds personal projects on weekends — learning by making, turning ideas into real things, the joy of creating." },
  { id: "g-pj-tools", topicId: "projects", title: "My Dev Setup", title_ja: "開発環境", emoji: "🧰", difficulty: "intermediate",
    summary: "The tools and stack you use.", summary_ja: "使っているツールとスタック。",
    brief: "Kaito's development setup and favorite stack (Next.js, React, FastAPI, Tailwind, OpenCV) and how he likes to work." },
  { id: "g-pj-dream", topicId: "projects", title: "My Dream Project", title_ja: "夢のプロジェクト", emoji: "✨", difficulty: "advanced",
    summary: "The app you'd love to build.", summary_ja: "いつか作りたいもの。",
    brief: "The dream project Kaito would love to build one day — something using AI to genuinely help people learn or live better." },

  // ───────── Future & Dreams ─────────
  { id: "g-ft-tenyears", topicId: "future", title: "Ten Years From Now", title_ja: "10年後", emoji: "🔭", difficulty: "advanced",
    summary: "Where you see yourself.", summary_ja: "10年後の自分。",
    brief: "Kaito imagines where he'll be in ten years — ideally an AI researcher, having earned a PhD, doing meaningful work." },
  { id: "g-ft-whyus", topicId: "future", title: "Why the US", title_ja: "なぜアメリカ", emoji: "🇺🇸", difficulty: "advanced",
    summary: "Why study abroad in the US.", summary_ja: "なぜ米国で学ぶのか。",
    brief: "Why Kaito wants to do a PhD in the US specifically — cutting-edge AI research, his past US exchange, working with top researchers." },
  { id: "g-ft-leaving", topicId: "future", title: "Leaving a Stable Job", title_ja: "安定を手放す", emoji: "🪜", difficulty: "advanced",
    summary: "The risk of chasing the dream.", summary_ja: "夢のためのリスク。",
    brief: "Kaito weighs the risk of leaving a stable job at Nissan to pursue a PhD and research career, and why he thinks it's worth it." },
  { id: "g-ft-impact", topicId: "future", title: "The Impact I Want", title_ja: "残したい影響", emoji: "🌍", difficulty: "advanced",
    summary: "Technology that helps society.", summary_ja: "社会の役に立つ技術。",
    brief: "The kind of impact Kaito hopes to have — building technology that genuinely helps society, not just makes money." },

  // ───────── Education ─────────
  { id: "g-ed-aizu", topicId: "education", title: "University of Aizu", title_ja: "会津大学", emoji: "🏫", difficulty: "intermediate",
    summary: "Your CS bachelor's years.", summary_ja: "学部時代の話。",
    brief: "Kaito's undergrad at the University of Aizu studying computer science — the international environment, his thesis on deep learning for optical fiber signals." },
  { id: "g-ed-rosehulman", topicId: "education", title: "My US Exchange", title_ja: "アメリカ交換留学", emoji: "🇺🇸", difficulty: "intermediate",
    summary: "3 months at Rose-Hulman.", summary_ja: "Rose-Hulmanでの3ヶ月。",
    brief: "Kaito's 3-month exchange at Rose-Hulman Institute of Technology in the US — data science classes, cross-cultural life, how it changed him." },
  { id: "g-ed-meijo", topicId: "education", title: "Starting Over", title_ja: "やり直し", emoji: "🔄", difficulty: "advanced",
    summary: "Dropping out and finding your path.", summary_ja: "中退して進路を見つけた話。",
    brief: "Kaito once dropped out of Meijo University (mechatronics) before going to Aizu. A reflective chat about changing direction and finding what he really wanted to study." },
  { id: "g-ed-study", topicId: "education", title: "How I Study", title_ja: "勉強のやり方", emoji: "📚", difficulty: "intermediate",
    summary: "Your independent study habits.", summary_ja: "独学のやり方。",
    brief: "How Kaito likes to learn — independently, by building, using AI tools and YouTube. His study habits and what works for him." },
  { id: "g-ed-favorite", topicId: "education", title: "My Favorite Subject", title_ja: "好きな科目", emoji: "🧮", difficulty: "beginner",
    summary: "The subjects you enjoyed most.", summary_ja: "一番好きだった科目。",
    brief: "The subjects Kaito enjoyed most in school and university, and why — leaning toward CS, AI, and math." },

  // ───────── English & Abroad ─────────
  { id: "g-en-why", topicId: "english", title: "Why I Learn English", title_ja: "英語を学ぶ理由", emoji: "🗣️", difficulty: "beginner",
    summary: "Your real reason for studying.", summary_ja: "英語学習の本当の理由。",
    brief: "Why Kaito studies English — not for tests, but to talk naturally with researchers and engineers abroad and to study overseas." },
  { id: "g-en-how", topicId: "english", title: "How I Practice", title_ja: "英語の練習法", emoji: "🎧", difficulty: "intermediate",
    summary: "Your English study routine.", summary_ja: "英語の勉強ルーティン。",
    brief: "How Kaito practices English day to day — YouTube, building this app, talking to AI, watching tech content in English." },
  { id: "g-en-struggle", topicId: "english", title: "My English Struggles", title_ja: "英語の苦労", emoji: "😅", difficulty: "intermediate",
    summary: "What's hard about English.", summary_ja: "英語で難しいこと。",
    brief: "The parts of English Kaito finds hard — speaking spontaneously, listening, confidence — and how he deals with them." },
  { id: "g-en-work", topicId: "english", title: "English at Work", title_ja: "仕事で使う英語", emoji: "💼", difficulty: "advanced",
    summary: "Using English on the job.", summary_ja: "仕事での英語。",
    brief: "How English shows up in Kaito's engineering work — reading papers, documentation, maybe global meetings — and why it matters for his career." },
  { id: "g-en-confidence", topicId: "english", title: "Speaking Confidently", title_ja: "自信を持って話す", emoji: "💪", difficulty: "intermediate",
    summary: "Getting comfortable speaking.", summary_ja: "話すことに慣れる。",
    brief: "Kaito talks about building confidence speaking English, making mistakes, and his goal of becoming comfortable in conversation." },

  // ───────── Food ─────────
  { id: "g-fd-kfc", topicId: "food", title: "My KFC Ritual", title_ja: "KFCの習慣", emoji: "🍗", difficulty: "beginner",
    summary: "Fried chicken once a week.", summary_ja: "週1のフライドチキン。",
    brief: "Kaito's weekly KFC habit — favorite order, why he loves it, his little weekend treat." },
  { id: "g-fd-ramen", topicId: "food", title: "Ramen Night", title_ja: "ラーメンの夜", emoji: "🍜", difficulty: "beginner",
    summary: "Your go-to ramen.", summary_ja: "お気に入りのラーメン。",
    brief: "Kaito talks about ramen — favorite type, a good shop near him, when he likes to eat it." },
  { id: "g-fd-cooking", topicId: "food", title: "Cooking for Myself", title_ja: "自炊", emoji: "🍳", difficulty: "intermediate",
    summary: "Simple meals you make.", summary_ja: "作る簡単な料理。",
    brief: "Whether Kaito cooks, what simple things he makes, and his relationship with cooking as a busy engineer." },
  { id: "g-fd-coffee", topicId: "food", title: "Coffee & Coding", title_ja: "コーヒーとコード", emoji: "☕", difficulty: "beginner",
    summary: "How you take your coffee.", summary_ja: "コーヒーの好み。",
    brief: "Kaito and coffee — how he takes it, whether it fuels his coding, cafe vs home." },
  { id: "g-fd-healthy", topicId: "food", title: "Eating Well", title_ja: "健康的な食事", emoji: "🥗", difficulty: "intermediate",
    summary: "Balancing health and KFC.", summary_ja: "健康とKFCのバランス。",
    brief: "Kaito tries to eat reasonably well despite the KFC habit — a light chat about health, balance, and busy-engineer eating." },

  // ───────── Travel ─────────
  { id: "g-tv-philippines", topicId: "travel", title: "My Trip to the Philippines", title_ja: "フィリピン旅行", emoji: "🏝️", difficulty: "intermediate",
    summary: "Your travel to the Philippines.", summary_ja: "フィリピンへの旅。",
    brief: "Kaito's trip to the Philippines — what he did, what stood out, the food and people." },
  { id: "g-tv-us", topicId: "travel", title: "Time in the US", title_ja: "アメリカ滞在", emoji: "🗽", difficulty: "intermediate",
    summary: "Living in the US during exchange.", summary_ja: "交換留学での米国生活。",
    brief: "Kaito's experience living in the US during his Rose-Hulman exchange — daily life, culture shock, favorite memories." },
  { id: "g-tv-dream", topicId: "travel", title: "Dream Destinations", title_ja: "行きたい場所", emoji: "🗺️", difficulty: "beginner",
    summary: "Places you want to visit.", summary_ja: "訪れたい場所。",
    brief: "Where Kaito dreams of traveling and why, including going back to the US for grad school." },
  { id: "g-tv-planes", topicId: "travel", title: "Flying & Airports", title_ja: "飛行機と空港", emoji: "✈️", difficulty: "beginner",
    summary: "How you feel about flying.", summary_ja: "飛行機について。",
    brief: "Kaito and flying — long flights, airports, how he passes the time, window or aisle." },

  // ───────── Daily Life ─────────
  { id: "g-dl-morning", topicId: "daily", title: "My Morning Routine", title_ja: "朝のルーティン", emoji: "🌅", difficulty: "beginner",
    summary: "How your day begins.", summary_ja: "一日の始まり方。",
    brief: "Kaito's morning routine before work — waking up, breakfast, getting ready, the commute." },
  { id: "g-dl-evening", topicId: "daily", title: "After Work", title_ja: "仕事のあと", emoji: "🌙", difficulty: "beginner",
    summary: "How you unwind in the evening.", summary_ja: "夜のくつろぎ方。",
    brief: "What Kaito does after work — dinner, side projects, YouTube, relaxing, before bed." },
  { id: "g-dl-atsugi", topicId: "daily", title: "Life in Atsugi", title_ja: "厚木暮らし", emoji: "🏙️", difficulty: "intermediate",
    summary: "Your neighborhood and routine.", summary_ja: "近所と生活。",
    brief: "Everyday life in Atsugi — the neighborhood, convenience stores, what's nearby, the rhythm of living there." },
  { id: "g-dl-health", topicId: "daily", title: "Staying Healthy", title_ja: "健康管理", emoji: "🏃", difficulty: "intermediate",
    summary: "Sleep, exercise, and balance.", summary_ja: "睡眠・運動・バランス。",
    brief: "How Kaito tries to stay healthy with a desk job — sleep, any exercise, screen time, balancing work and rest." },
  { id: "g-dl-money", topicId: "daily", title: "Spending & Saving", title_ja: "お金の使い方", emoji: "💴", difficulty: "intermediate",
    summary: "What you spend on.", summary_ja: "お金をかけるもの。",
    brief: "A light chat about what Kaito likes to spend money on (gadgets, courses, KFC) and saving up for the future, like grad school. Avoid sensitive financial detail." },
];
