import type { Topic } from "@/lib/types";

/**
 * Static conversation trees for the MVP.
 * Later these can be augmented / generated by an LLM while keeping the same shape.
 */
export const topics: Topic[] = [
  {
    id: "self-intro",
    emoji: "👋",
    title_en: "Self Introduction",
    title_ja: "自己紹介",
    opening: {
      en: "Hi! Nice to meet you. Can you tell me a little about yourself?",
      ja: "こんにちは！はじめまして。少し自己紹介してくれますか？",
    },
    branches: [
      {
        id: "si-student",
        label_en: "I'm a student",
        label_ja: "学生です",
        emoji: "🎓",
        questions: [
          {
            id: "si-student-q1",
            en: "What do you study?",
            ja: "何を勉強していますか？",
            examples: {
              beginner: "I study computer science.",
              intermediate: "I'm studying computer science at university.",
              advanced:
                "I'm majoring in computer science, and I'm especially interested in artificial intelligence.",
            },
          },
          {
            id: "si-student-q2",
            en: "What year are you in?",
            ja: "何年生ですか？",
            examples: {
              beginner: "I'm a third-year student.",
              intermediate: "I'm in my third year of university.",
              advanced:
                "I'm a third-year student, so I'm starting to think seriously about my career.",
            },
          },
          {
            id: "si-student-q3",
            en: "What do you like about your studies?",
            ja: "勉強のどんなところが好きですか？",
            examples: {
              beginner: "I like coding.",
              intermediate: "I really enjoy building things with code.",
              advanced:
                "I love how programming lets me turn an idea into something real that other people can actually use.",
            },
          },
        ],
      },
      {
        id: "si-work",
        label_en: "I'm working",
        label_ja: "働いています",
        emoji: "💼",
        questions: [
          {
            id: "si-work-q1",
            en: "What kind of work do you do?",
            ja: "どんな仕事をしていますか？",
            examples: {
              beginner: "I'm an engineer.",
              intermediate: "I work as a software engineer.",
              advanced:
                "I work as a software engineer, mainly building web applications for our customers.",
            },
          },
          {
            id: "si-work-q2",
            en: "How long have you been doing it?",
            ja: "どのくらいその仕事をしていますか？",
            examples: {
              beginner: "About two years.",
              intermediate: "I've been doing it for about two years.",
              advanced:
                "I've been in this role for about two years, and I'm still learning something new almost every day.",
            },
          },
        ],
      },
      {
        id: "si-hobby",
        label_en: "Let me tell you my hobby",
        label_ja: "趣味を話します",
        emoji: "🎮",
        questions: [
          {
            id: "si-hobby-q1",
            en: "What do you like to do in your free time?",
            ja: "自由な時間に何をするのが好きですか？",
            examples: {
              beginner: "I like playing games.",
              intermediate: "In my free time, I usually play video games.",
              advanced:
                "When I have free time, I like playing video games because it helps me relax and disconnect.",
            },
          },
          {
            id: "si-hobby-q2",
            en: "How did you get into it?",
            ja: "どうやってそれを始めたのですか？",
            examples: {
              beginner: "My friend showed me.",
              intermediate: "A friend introduced me to it a few years ago.",
              advanced:
                "A close friend got me into it a few years ago, and I've been hooked ever since.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "weekend",
    emoji: "🛋️",
    title_en: "Weekend",
    title_ja: "週末",
    opening: {
      en: "What do you usually do on weekends?",
      ja: "週末はたいてい何をしていますか？",
    },
    branches: [
      {
        id: "wk-youtube",
        label_en: "Watch YouTube",
        label_ja: "YouTubeを見る",
        emoji: "📺",
        questions: [
          {
            id: "wk-yt-q1",
            en: "What kind of videos do you watch?",
            ja: "どんな動画を見ますか？",
            examples: {
              beginner: "I watch AI videos.",
              intermediate: "I mostly watch videos about AI and technology.",
              advanced:
                "I mainly watch videos about AI and technology because I like keeping up with the latest tools.",
            },
          },
          {
            id: "wk-yt-q2",
            en: "Who is your favorite YouTuber?",
            ja: "好きなYouTuberは誰ですか？",
            examples: {
              beginner: "I like Mr. Beast.",
              intermediate: "My favorite YouTuber is a tech reviewer named MKBHD.",
              advanced:
                "My favorite is probably MKBHD because his videos are really well made and easy to understand.",
            },
          },
          {
            id: "wk-yt-q3",
            en: "How often do you watch YouTube?",
            ja: "どのくらいの頻度でYouTubeを見ますか？",
            examples: {
              beginner: "Every day.",
              intermediate: "I watch it almost every day.",
              advanced:
                "Pretty much every day, usually for an hour or so before I go to sleep.",
            },
          },
          {
            id: "wk-yt-q4",
            en: "What did you watch yesterday?",
            ja: "昨日は何を見ましたか？",
            examples: {
              beginner: "I watched a game video.",
              intermediate: "Yesterday I watched a video about a new AI model.",
              advanced:
                "Yesterday I watched a long video comparing a few new AI models, and it was surprisingly interesting.",
            },
          },
        ],
      },
      {
        id: "wk-kfc",
        label_en: "Go to KFC",
        label_ja: "KFCに行く",
        emoji: "🍗",
        questions: [
          {
            id: "wk-kfc-q1",
            en: "How often do you go there?",
            ja: "どのくらいの頻度で行きますか？",
            examples: {
              beginner: "Every weekend.",
              intermediate: "I go there almost every weekend.",
              advanced:
                "I go there most weekends — it's kind of become a little ritual for me.",
            },
          },
          {
            id: "wk-kfc-q2",
            en: "What's your favorite menu item?",
            ja: "好きなメニューは何ですか？",
            examples: {
              beginner: "Fried chicken.",
              intermediate: "My favorite is the original fried chicken.",
              advanced:
                "My favorite is the original recipe chicken, but I always add some biscuits on the side.",
            },
          },
          {
            id: "wk-kfc-q3",
            en: "Do you usually go alone?",
            ja: "たいてい一人で行きますか？",
            examples: {
              beginner: "Yes, alone.",
              intermediate: "Usually I go alone, but sometimes with friends.",
              advanced:
                "Most of the time I go alone, but every now and then I'll grab a bucket with friends.",
            },
          },
        ],
      },
      {
        id: "wk-games",
        label_en: "Play games",
        label_ja: "ゲームをする",
        emoji: "🎮",
        questions: [
          {
            id: "wk-game-q1",
            en: "What games do you play?",
            ja: "どんなゲームをしますか？",
            examples: {
              beginner: "I play RPGs.",
              intermediate: "I mostly play role-playing games.",
              advanced:
                "I mostly play RPGs and the occasional shooter when I want something fast-paced.",
            },
          },
          {
            id: "wk-game-q2",
            en: "Steam or Switch?",
            ja: "SteamとSwitchどちらですか？",
            examples: {
              beginner: "Switch.",
              intermediate: "I play on Switch more often.",
              advanced:
                "I use both, but I reach for the Switch more because I can play it in bed.",
            },
          },
          {
            id: "wk-game-q3",
            en: "Do you play multiplayer?",
            ja: "マルチプレイはしますか？",
            examples: {
              beginner: "Yes, with friends.",
              intermediate: "Yes, I usually play online with friends.",
              advanced:
                "Yeah, I mostly play online with friends — it's more about hanging out than the game itself.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "food",
    emoji: "🍜",
    title_en: "Food",
    title_ja: "食べ物",
    opening: {
      en: "What's your favorite food?",
      ja: "好きな食べ物は何ですか？",
    },
    branches: [
      {
        id: "fd-ramen",
        label_en: "I love ramen",
        label_ja: "ラーメンが大好き",
        emoji: "🍜",
        questions: [
          {
            id: "fd-ramen-q1",
            en: "What kind of ramen do you like?",
            ja: "どんなラーメンが好きですか？",
            examples: {
              beginner: "I like tonkotsu.",
              intermediate: "I really like rich tonkotsu ramen.",
              advanced:
                "I love tonkotsu ramen the most, especially when the broth is really thick and creamy.",
            },
          },
          {
            id: "fd-ramen-q2",
            en: "Do you have a favorite shop?",
            ja: "お気に入りのお店はありますか？",
            examples: {
              beginner: "Yes, near my house.",
              intermediate: "Yes, there's a great shop near my house.",
              advanced:
                "There's a small family-run shop near my house that I keep going back to — the owner remembers my order now.",
            },
          },
        ],
      },
      {
        id: "fd-cook",
        label_en: "I like cooking",
        label_ja: "料理が好き",
        emoji: "🍳",
        questions: [
          {
            id: "fd-cook-q1",
            en: "What do you usually cook?",
            ja: "普段は何を作りますか？",
            examples: {
              beginner: "I cook pasta.",
              intermediate: "I usually make simple pasta dishes.",
              advanced:
                "I usually cook pasta or curry because they're easy to make in large batches for the week.",
            },
          },
          {
            id: "fd-cook-q2",
            en: "Who taught you to cook?",
            ja: "誰に料理を教わりましたか？",
            examples: {
              beginner: "My mother.",
              intermediate: "My mom taught me when I was young.",
              advanced:
                "My mom taught me the basics growing up, and I learned the rest from YouTube videos.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "travel",
    emoji: "✈️",
    title_en: "Travel",
    title_ja: "旅行",
    opening: {
      en: "Do you like to travel?",
      ja: "旅行は好きですか？",
    },
    branches: [
      {
        id: "tv-yes",
        label_en: "Yes, I love it",
        label_ja: "はい、大好きです",
        emoji: "🌍",
        questions: [
          {
            id: "tv-yes-q1",
            en: "Where have you traveled recently?",
            ja: "最近どこに旅行しましたか？",
            examples: {
              beginner: "I went to Osaka.",
              intermediate: "I recently took a trip to Osaka.",
              advanced:
                "I recently went to Osaka for a few days, mostly to eat my way through the city.",
            },
          },
          {
            id: "tv-yes-q2",
            en: "What's your dream destination?",
            ja: "夢の旅行先はどこですか？",
            examples: {
              beginner: "I want to go to Italy.",
              intermediate: "My dream destination is Italy.",
              advanced:
                "My dream destination is Italy — I'd love to spend a few weeks just exploring small towns and eating.",
            },
          },
        ],
      },
      {
        id: "tv-home",
        label_en: "I prefer staying home",
        label_ja: "家にいる方が好き",
        emoji: "🏠",
        questions: [
          {
            id: "tv-home-q1",
            en: "What do you like to do at home?",
            ja: "家では何をするのが好きですか？",
            examples: {
              beginner: "I watch movies.",
              intermediate: "I like watching movies and relaxing.",
              advanced:
                "I like watching movies, reading, and just having a slow, quiet day with no plans.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "technology",
    emoji: "💻",
    title_en: "Technology",
    title_ja: "テクノロジー",
    opening: {
      en: "Are you interested in technology?",
      ja: "テクノロジーに興味はありますか？",
    },
    branches: [
      {
        id: "tc-ai",
        label_en: "I'm really into AI",
        label_ja: "AIにとても興味がある",
        emoji: "🤖",
        questions: [
          {
            id: "tc-ai-q1",
            en: "How do you use AI in your daily life?",
            ja: "日常生活でAIをどう使っていますか？",
            examples: {
              beginner: "I use ChatGPT.",
              intermediate: "I use AI chatbots to help me study.",
              advanced:
                "I use AI tools every day — for studying English, writing code, and even planning my schedule.",
            },
          },
          {
            id: "tc-ai-q2",
            en: "What excites you most about AI?",
            ja: "AIの何に一番ワクワクしますか？",
            examples: {
              beginner: "It's very useful.",
              intermediate: "I think it can make life much easier.",
              advanced:
                "What excites me most is how quickly it's improving — it feels like the future is arriving faster than expected.",
            },
          },
        ],
      },
      {
        id: "tc-gadget",
        label_en: "I love gadgets",
        label_ja: "ガジェットが好き",
        emoji: "📱",
        questions: [
          {
            id: "tc-gadget-q1",
            en: "What's your favorite gadget?",
            ja: "好きなガジェットは何ですか？",
            examples: {
              beginner: "My phone.",
              intermediate: "My favorite gadget is my smartphone.",
              advanced:
                "Probably my smartphone — it's the one device I genuinely couldn't get through the day without.",
            },
          },
        ],
      },
    ],
  },
];

export const topicById = (id: string) => topics.find((t) => t.id === id);
